# Generated by Django 5.2.4 on 2025-08-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'permissions': [('can_unpublish_product', 'Может отменять публикацию товара')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
